import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image';

import RecoilProvider from './recoilProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image src="/back.jpg" layout="fill" objectFit="cover" alt="back" style={{ opacity: 0.5, zIndex: -1 }} />
          <RecoilProvider>{children}</RecoilProvider>
      </body>
    </html>
  );
}
